name: Extrator RePEc

on:
  workflow_dispatch:

jobs:
  rodar-script:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Instalar bibliotecas
        run: pip install requests beautifulsoup4 pandas openpyxl
      - name: Executar Script
        run: python script_extract.py
      - name: Salvar resultados
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add Dados_Completos_RePEc.xlsx Lista_Handles_RePEc.csv || echo "Arquivos não criados"
          git commit -m "Atualizando base de dados" || echo "Sem alterações"
          git push
